ALTER TABLE public.promo_codes
ADD COLUMN max_uses INTEGER NOT NULL DEFAULT 1,
ADD COLUMN times_used INTEGER NOT NULL DEFAULT 0,
ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN discount_type TEXT NULL,
ADD COLUMN discount_value NUMERIC NULL,
ADD COLUMN metadata JSONB NULL;
